config/routes.rb
Tinyplanet::Application.routes.draw do
  

  devise_for :users

  get '/' => 'main#index'

  post '/save' => 'main#save'

  post '/serve' => 'main#serve'

  post '/favorite' => 'main#favorite'

  post '/like' => 'main#like'

  get '/liked' => 'main#liked?'

  get '/comboserve' => 'main#comboserve'

end

app/models/combo.rb
class Combo < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :songs
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :combo
  belongs_to :user
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
  # attr_accessible :title, :body
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :opinions
  has_many :users, through: :opinions
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :combos, through: :favorites 
  has_many :songs, through: :opinions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login
  # attr_accessible :title, :body

  attr_accessor :login

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout "application"
    protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def serve
        # returns an array of one, [0]] could be .first
        @combo = Combo.where("city = ? AND genre = ?", params[:city],params[:genre])[0]
        if @combo == nil
          @client = SoundCloud.new(:client_id => '4c2a3b5840e0236549608f59c2cd7d07')
          @tracks = @client.get('/tracks', q: params[:city], genres: params[:genre], filter: 'streamable')

          @combo = Combo.new
          @combo.city = params[:city]
          @combo.genre = params[:genre]
          @combo.save

          @tracks.each do |track|
            song = Song.new
            song.combo_id = @combo.id
            song.name = track.title
            song.url = "#{track.stream_url}?client_id=4c2a3b5840e0236549608f59c2cd7d07"
            song.soundcloud_id = track.id
            # default artwork
            song.artwork_url = track.artwork_url || 'http://icons.iconarchive.com/icons/dan-wiersma/solar-system/512/Uranus-icon.png'
            song.artwork_url = song.artwork_url.gsub("large", "t300x300")
            song.artist = track.user.username
            song.save if track.stream_url
          end
        end
        unliked = []
        liked = []
        liked_most = 0
        high_count = 0
        @combo.songs.each do |song|
            if song.users.count == 0
                unliked.push(song)
            else
                liked.push(song)
            end
        end

        liked.shuffle!
        unliked.shuffle!
        rand_front = unliked.shift(liked.length * 2)
        rand_front += liked
        rand_front.shuffle!
        # if liked_most != 0  
        #   rand_front.unshift(liked_most)
        # else
        #   puts "No songs liked in this scene yet :("
        # end
        @playlist = rand_front + unliked
        # @playlist.each do |song|
        #     if song == 0
        #         binding.pry
        #     end
        # end
         respond_to do |format| 
          format.json { render :json => @playlist.to_json }
        end
    end
    

    def index
    end

    def like
        found = Opinion.where("song_id = ? AND user_id = ?", params[:song_id], current_user)
        if found == []
            opinion = Opinion.new
            opinion.song_id = Song.find(params[:song_id]).id
            opinion.user = current_user
            opinion.enjoyed = true
            opinion.save
        else
            found[0].delete
        end
        liked?
    end

    def liked?
        @liked = Opinion.where("song_id = ? AND user_id = ?", params[:song_id], current_user)[0]
        respond_to do |format| 
          format.json { render :json => @liked.to_json }
        end
    end


    def favorite
        @combo = Combo.where("city = ? AND genre = ?", params[:city],params[:genre])[0]
        unless @combo == nil
            favorite = Favorite.new
            favorite.user = current_user
            favorite.combo = @combo
            favorite.save!
        else
            find[0].destroy
        end
        comboserve
    end


    def comboserve
        render json: current_user.combos.to_json
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TinyPlanet.fm</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <link href='http://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>   
    <%= render "users/login_modal" %>

    <%= render "users/sign_up_modal" %>
    <%= render 'users/edit_modal' %>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">tinyplanet.fm</h3>
              
              <ul class="nav masthead-nav">
                <% if user_signed_in? %>
                  <li class="active"> <%= link_to current_user.username, "/#edit", "data-toggle" => "modal"  %>
                  </li>
                  <li><%= link_to "sign out", destroy_user_session_path, :method => :delete %></li>
                <% else %>
                  <li class="active"><%= link_to "Login", "#login", "data-toggle" => "modal" %></li>
                  <li><%= link_to "sign up", "#sign_up", "data-toggle" => "modal"%> </li>  
                <% end %>
              </ul>
            
            </div>
            <!-- END inner DIV -->
          </div>
          <!-- END masthead clearfix DIV -->
        </div>
        <!-- END cover-container DIV -->

        <div class="container">
          <%= yield %> 
        </div>
        <!-- END container DIV -->

      </div>
      <!-- END site-wrapper-inner DIV -->
    </div>
    <!-- END site-wrapper DIV -->

    <!-- <div id="stripes-div">
      <div id="stripe3"></div>
      <div id="stripe2"></div>
      <div id="stripe1"></div> 
    </div> --><!-- END stripes-div DIV -->

  </body>
  
</html>

app/views/main/_landing.html.erb
	<%= render "users/login_modal" %>

	<%= render "users/sign_up_modal" %>

	<div class="site-wrapper">

		<div class="site-wrapper-inner">

			<div class="cover-container">

				<div class="masthead clearfix">
					<div class="inner">
						<h3 class="masthead-brand">tinyplanet.fm</h3>
						<ul class="nav masthead-nav">
							<li class="active"><%= link_to "Login", "#login", "data-toggle" => "modal" %></li>

							<li><%= link_to "Sign up", "#sign_up", "data-toggle" => "modal"%> </li>

						</ul>
					</div>
				</div>

				<div class="inner cover">
					<h1 class="cover-heading">Make a Scene.</h1>
					<p class="lead">ever wonder about what music you might be missing out on? with tinyplanet.fm, you can search, like, and find local artists playing the music you want to here. </p>
					<p class="lead">
						<a href="#" class="btn btn-lg btn-default">Get Started</a>
					</p>
				</div>
			<!-- 	<div class="make-scene">
					<p>I'm listening to the...</p>
					<input name='genre' id='genre' class="form-control" placeholder='scene'></input>
					<br>
					<p>in...</p>
					<input name='city' class='form-control' id='city' placeholder='city'></input>
				</div>



				<div id="player" class="col-xs-8 col-xs-offset-2">
					<div id="album art">
						I AM ART
					</div>

					<div id="song-info">
						I AM SONG NAME
					</div>

					<div id="controls">
						<i class="fa fa-play glyphicon-large" id="play"></i>
						<i class="fa fa-pause glyphicon-large" id="pause"></i>
						<i class="fa fa-ban glyphicon-large" id="next"></i>
						<i class="fa fa-heart glyphicon-large" id="heart"></i>
						<i class="fa fa-heart-o glyphicon-large" id="openheart"> </i>
						<i class="fa fa-rocket glyphicon-large" id="share"></i>
					</div>
					<div id="share-like">
						<span id="favorite" class></span>
					</div> -->

				</div>
			</div>
		</div>

app/views/main/index.html.erb
<div class="inner cover">
  <% unless user_signed_in? %>
  <h1 class="cover-heading">Make a Scene.</h1>
  <p class="lead">ever wonder what music you might be missing out on? with tinyplanet.fm you can find, like, and share local artists playing the music you want, anywhere. </p>
  <p class="lead">
    <a class="btn btn-lg btn-default" data-toggle="modal" data-target="#sign_up">Start Listening</a>
  </p>
</div><!-- END inner cover DIV -->

<% else %>





<div class="row">

  <div class="make-scene col-lg-4">
    <p>I'm listening to the...</p>
    <input name='genre' id='genre' class="form-control" placeholder='scene'></input>
    <br>
    <p>scene in...</p>
    <input name='city' class='form-control' id='city' placeholder='city'></input>
    <div class="row">
      <div class= "col-lg-12">
        <a class="btn btn-sm btn-default btn-make" id="makecombo">make the scene</a>
        <a class="btn btn-sm btn-default btn-make" id="savecombo">save the scene</a>
      </div>
    </div>
      <div class ="row favscene">
    <p class="lead"> your favorite scenes:</p>
      <div id="userscombos">
    </div>
    </div>
  </div><!-- END make-scene DIV -->

  <div id="player" class="col-lg-8 hide">

    <div class="row">

      <div id="album-cover" class="col-lg-6 text-centered">
        <div id="cover" style="background: url('http://placekitten.com/300/300'); width:300px; height:300px; background-size:cover;">
          <i id="current-heart" class="fa fa-heart-o icon pos-absolute text-shadow"></i>
          <div id="inner-box">
            <i id="play" class="fa fa-play icon pos-absolute text-shadow"></i>
            <i id="pause" class="fa fa-pause icon pos-absolute text-shadow"></i>
            <i id="next" class="fa fa-forward icon pos-absolute text-shadow"></i>
          </div>
        </div>
      </div><!-- END album-cover DIV -->

      <div class="album-descriptors col-lg-5 text-centered">
        <h4 id="artist-info">

        </h4>
        <h4 id="song-info">
          Song:
        </h4>
      <p id="currentscene"> the scene in....</p>
      <div class="instagram">
      </div>
    </div>
  </div>

      </div><!-- END album-descriptors DIV -->

    </div><!-- END row DIV -->
  </div><!-- END player DIV -->
</div><!-- END row DIV -->





<div class="mastfoot hidden"> 
  <div class="row">
    <div id="last-played-div inner" class="col-lg-8">
      <h4>you last played:</h4> 
      <div id="last-played-content" class="row">
        <div class="col-lg-6">  
          <h5 id="lastSong" class="no-margin-top"></h5> 
        </div>
        <div class="col-lg-6">
          <i id="last-heart" class="fa fa-heart-o icon"></i>        
          <!--  <i id="last-rocket" class="icon fa fa-rocket "></i> -->
        </div>
      </div><!-- END last-played-content DIV -->
    </div><!-- END last-played-div inner DIV -->
   </div>
</div><!-- END mastfoot DIV -->

<% end %>

app/views/users/_edit_modal.html.erb
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

<div class="modal-header">
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<button class="close" data-dismiss="modal">x</button>



</div>

<div class="modal-body">

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>

  <div class="form-inputs">
    <div><%= f.label :username %><br />

    <%= f.text_field :username, :required => true, :autofocus => true %></div>

    <div><%= f.label :email %><br />
    <%= f.text_field :email, :required => true, :autofocus => true %></div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>

    <div><%= f.label :password %><br />
    <%= f.text_field :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false %></div>

    <div><%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation, :required => false %></div>

    <div><%= f.label :current_password %><br />
    <%= f.text_field :current_password, :hint => "we need your current password to confirm your changes", :required => true %></div>
  </div>
<br />
  <%= f.submit "update", :class => 'btn btn-small btn-success' %>
  <% end %>
<br />
<p>unhappy? you can always <%= link_to "cancel your account", registration_path(resource_name), :data => { :confirm => "are you sure?" }, :method => :delete %> (but it won't fix anything)</p>
</div>

<div class="modal-footer">

<%= render "devise/shared/links" %>

</div>


</div>
</div>
</div>
</div>

app/views/users/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

<div class="modal-header">
sign in

<button class="close" data-dismiss="modal">x</button>



</div>

<div class="modal-body">

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

<div><%= f.label :login %><br />

<%= f.text_field :login, :autofocus => true %></div>

<div><%= f.label :password %><br />

<%= f.password_field :password %></div>

<% if devise_mapping.rememberable? -%>

<div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>

<% end %>

<%= f.submit "Sign In", :class => 'btn btn-small btn-success' %>
<% end %>

</div>

<div class="modal-footer">

<%= render "devise/shared/links" %>

</div>


</div>
</div>
</div>
</div>

app/views/users/_sign_up_modal.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

<div class="modal-header">
Sign Up

<button class="close" data-dismiss="modal">x</button>



</div>

<div class="modal-body">
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

<%= devise_error_messages! %>
<div><%= f.label :username %><br />

<%= f.text_field :username, :autofocus => true %></div>

<div><%= f.label :email %><br />

<%= f.email_field :email, :autofocus => true %></div>

<div><%= f.label :password %><br />

<%= f.password_field :password %></div>

<div><%= f.label :password_confirmation %><br />

<%= f.password_field :password_confirmation %></div>

</div>

<div class="modal-footer">

<p><div><%= f.submit "Sign Up", :class => 'btn btn-small btn-success' %></div></p>

<p><a href="#" class="btn btn-small" data-dismiss="modal">Close</a></p>

</div>
<% end %>


</div>
</div>
</div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign In", new_session_path(resource_name), class: 'btn btn-primary' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to "Sign Up", "#sign_up", "data-toggle" => "modal"%>
<!--   <%= link_to "Sign Up", new_registration_path(resource_name) %> --><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>